### ISSUE TITLE
review_lesson-1

### ISSUE THREAD

**Issue by alexey100196** [Yureyko228/teymax_lesson1#2]
[review_lesson-1_Yureyko228.odt](https://github.com/Yureyko228/teymax_lesson1/files/7504281/review_lesson-1_Yureyko228.odt)

**Comment by Yureyko228** [comment]
Якоря добавил ;
Методалогию БЕМ просмотрел и немного попрактиковал в другом проекте , в этом проекте уже не делал так как очень много переделовать ;
Номер записал в тег а и сам номер в href;
Футор не получилось адекватно прикрепить к низу , например если без контента ему дать position:absolute; width:100%; bottom:0; то все работает , но если вернуть назад контент , все поплывет . Так же перепробовал пару методов с гугла ;
Стили подключил через импорт;

P.s Все фиксы и демо адаптив на ветке lesson2)

**Comment by alexey100196** [comment]
good job!
